[package]
name = "apply"
version = "0.3.0"
authors = ["George Burton <burtonageo@gmail.com>"]
description = "A tiny library for chaining free functions into method call chains."
readme = "./Readme.md"
repository = "https://github.com/burtonageo/apply"
license_file = "./License.md"
